words =[ "ability", "absence", "academy", "account", "accuse", "achieve", "acquire", "address", "advance", "adviser",
    "airline", "airport", "alcohol", "allege", "already", "amazing", "analyze", "ancestor", "announce", "anxious",
    "apology", "applaud", "appoint", "approve", "arrange", "arrival", "article", "artwork", "assault", "assume",
    "astonish", "athlete", "attempt", "attract", "auction", "average", "awesome", "backpack", "baggage", "balance",
    "ballet", "barrier", "battery", "beautiful", "behavior", "birthday", "boundary", "building", "business", "butterfly",
    "calendar", "campaign", "capacity", "casualty", "celebrate", "challenge", "champion", "character", "chemical", "civilization",
    "clarify", "classroom", "clothing", "collapse", "commerce", "committee", "community", "companion", "compete", "complaint",
    "complex", "composer", "computer", "conclude", "confident", "conscious", "consider", "constant", "construct", "consult",
    "contact", "continue", "contract", "contrast", "contribute", "convince", "cooperate", "coordinate", "corporate", "council",
    "courage", "courtesy", "creation", "creative", "criminal", "criticism", "cultural", "curiosity", "customer", "dangerous",
    "database", "deadline", "decision", "decorate", "dedicate", "definite", "delicate", "delivery", "democracy", "describe",
    "designer", "detailed", "determine", "dialogue", "difficult", "dinosaur", "discovery", "distance", "distinct", "district",
    "diverse", "document", "dominate", "donation", "downward", "dramatic", "economic", "education", "effective", "efficient",
    "election", "elevator", "eliminate", "embarrass", "emergency", "emotional", "emphasize", "encourage", "engineer", "enormous",
    "entertain", "envelope", "equality", "equipment", "essential", "establish", "evaluate", "everybody", "excellent", "exception",
    "exchange", "exercise", "exhausted", "existence", "expansion", "experience", "explosion", "expression", "extension", "fantastic",
    "fascinate", "festival", "fireplace", "flexible", "fortunate", "furniture", "generation", "gentleman", "governor", "graduate",
    "grandfather", "greenhouse", "guarantee", "handwriting", "happiness", "harmless", "headquarters", "healthcare", "historian", "hospital",
    "household", "illustrate", "immediate", "important", "impression", "improvement", "individual", "industrial", "influence", "informative",
    "ingredient", "innovation", "insurance", "intelligent", "intention", "introduce", "investigate", "invitation", "involvement", "journalist",
    "judgment", "landscape", "leadership", "literature", "mainstream", "management", "manufacturer", "mathematics", "mechanical", "medication",
    "membership", "motivation", "negotiate", "newspaper", "nightmare", "objective", "obligation", "occupation", "operation", "opposition",
    "opportunity", "organization", "original", "partnership", "performance", "permanent", "perspective", "philosophy", "photograph", "political",
    "population", "possession", "preference", "preparation", "presentation", "president", "productive", "professional", "programming", "proportion",
    "protection", "psychology", "qualification", "recognition", "recommendation", "reduction", "reflection", "refrigerator", "regulation", "relationship",
    "replacement", "representation", "requirement", "residential", "responsibility", "restaurant", "revolution", "satisfaction", "significant", "situation",
    "sophisticated", "specialist", "spectacular", "spokesperson", "statistics", "strategic", "substantial", "successful", "sufficient", "supermarket",
    "technology", "temperature", "tournament", "traditional", "transportation", "understanding", "unfortunate", "university", "valuable", "vegetable",
    "vocabulary", "warehouse", "widespread", "wonderful", "workplace", "worthwhile", "yesterday", "youthful", "zebra", "xylophone", "zealous", "yawn",
    "wizard", "voyage", "ultimate", "tornado", "symphony", "radiance", "harmony", "adventure", "sunshine", "moonlight", "whisper", "cascade",
    "tranquil", "butterscotch", "chandelier", "flourish", "glimmer", "lullaby", "mystique", "nostalgia", "paradise", "serenade",
    "magnificent", "serendipity", "labyrinth", "silhouette", "phenomenon", "ephemeral", "solitude", "quintessential", "melancholy", "effervescent",
    "epiphany", "incandescent", "ineffable", "luminous", "euphoria", "halcyon", "sonorous", "rendezvous", "belvedere", "panacea", "aardvark", "baboon", "camel", "ant", "gorilla"]